"use client";
import { useEffect, useState } from "react";
import { adminRequest } from "./admin-api";
import styles from "./admin.module.css";

interface SecurityState { mfaEnabled: boolean; sharedProtection: boolean; emailReady: boolean; siteUrl: string; origin: string }
export function AdminSecurity() {
  const [status, setStatus] = useState<SecurityState | null>(null);
  const [setup, setSetup] = useState<{ qr: string; secret: string } | null>(null);
  const [pending, setPending] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); adminRequest<SecurityState>("/admin/security", { signal: controller.signal }).then(setStatus).catch((caught) => { if (!controller.signal.aborted) setError(caught.message); }); return () => controller.abort(); }, []);
  async function enroll(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setPending(true); setError("");
    try { setSetup(await adminRequest("/admin/security/mfa/enroll", { method: "POST", body: JSON.stringify({ password: data.get("password") }) })); form.reset(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "تعذّر الإعداد."); }
    finally { setPending(false); }
  }
  async function confirm(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); setPending(true); setError("");
    try { await adminRequest("/admin/security/mfa/confirm", { method: "POST", body: JSON.stringify({ code: data.get("code") }) }); setSetup(null); setStatus((previous) => previous ? { ...previous, mfaEnabled: true } : previous); setMessage("تم تفعيل التحقق بخطوتين وإلغاء الجلسات القديمة."); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "تعذّر التحقق."); }
    finally { setPending(false); }
  }
  async function backup() {
    setPending(true); setError("");
    try { const data = await adminRequest("/admin/backup"); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `portfolio-content-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "تعذّر التصدير."); }
    finally { setPending(false); }
  }
  async function validateBackup(file?: File) {
    if (!file) return; setError(""); setMessage("");
    if (file.size > 4 * 1024 * 1024) { setError("حد الملف 4 ميجابايت."); return; }
    setPending(true);
    try { const content = JSON.parse(await file.text()); const result = await adminRequest<{ records: number }>("/admin/backup/validate", { method: "POST", body: JSON.stringify(content) }); setMessage(`النسخة سليمة وتحتوي على ${result.records} عنصرًا. هذا فحص فقط؛ لم يتغير محتوى الموقع.`); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "ملف غير صالح."); }
    finally { setPending(false); }
  }
  const qr = setup?.qr.startsWith("<svg") ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(setup.qr)}` : setup?.qr.startsWith("data:image/svg+xml") ? setup.qr : undefined;
  return <div className={styles.securityGrid}>
    {error ? <p className={styles.noticeError} role="alert">{error}</p> : null}{message ? <p className={styles.notice} role="status">{message}</p> : null}
    <section className={styles.securityPanel}><h2>حماية الحساب</h2><p>أضف رمزًا متغيّرًا من تطبيق المصادقة بجانب كلمة المرور.</p>
      {!status ? <p>جارٍ فحص الحالة…</p> : status.mfaEnabled ? <p>التحقق بخطوتين مفعّل ✓</p> : setup ? <form className={styles.loginForm} onSubmit={confirm}>
        {/* QR generated by Supabase Auth, rendered as an inert image rather than HTML. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        {qr ? <img className={styles.mfaQr} src={qr} width={220} height={220} alt="امسح الرمز باستخدام تطبيق المصادقة" /> : null}
        <details><summary>إدخال المفتاح يدويًا</summary><code dir="ltr">{setup.secret}</code></details>
        <p>احتفظ بنسخة آمنة داخل تطبيق المصادقة. فقدانه يحتاج استعادة الوصول من مالك مشروع Supabase.</p>
        <label>رمز التحقق<input name="code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} dir="ltr" required /></label><button className={styles.saveButton} disabled={pending}>تأكيد التفعيل</button>
      </form> : <form onSubmit={enroll} className={styles.loginForm}><label>كلمة المرور الحالية<input name="password" type="password" autoComplete="current-password" required /></label><button className={styles.saveButton} disabled={pending}>إعداد التحقق بخطوتين</button></form>}
    </section>
    <section className={styles.securityPanel}><h2>جاهزية التشغيل</h2><ul><li>حماية الطلبات المشتركة: {status ? status.sharedProtection ? "جاهزة" : "تحتاج تطبيق ملف SQL الجديد" : "جارٍ الفحص"}</li><li>بريد التنبيهات والاستعادة: {status ? status.emailReady ? "المفاتيح مهيأة؛ اختبر وصول البريد" : "يحتاج إعداد Resend وبريد إرسال موثّق" : "جارٍ الفحص"}</li></ul><p>النطاق المضبوط: <bdi>{status?.siteUrl || "غير مضبوط"}</bdi></p><p>نطاق الدخول: <bdi>{status?.origin}</bdi></p><p>تسجيل الخروج يلغي جميع جلسات لوحة الإدارة.</p></section>
    <section className={styles.securityPanel}><h2>نسخة من المحتوى</h2><p>تصدير نصوص الموقع والمشاريع والمقالات، بما فيها المسودات. الصور تُحفظ كروابط؛ يلزم نسخ ملفات Storage وقاعدة البيانات بشكل منفصل.</p><button type="button" className={styles.saveButton} disabled={pending} onClick={() => void backup()}>تنزيل نسخة JSON</button><label className={styles.backupField}>فحص نسخة احتياطية دون تغيير الموقع<input type="file" accept="application/json,.json" disabled={pending} onChange={(event) => void validateBackup(event.target.files?.[0])} /></label></section>
  </div>;
}
